// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"user-service/internal/controller"
	"user-service/internal/repositories"
	"user-service/internal/services"
	"user-service/pkg/utils/copyhelper"
)

// Injectors from user_wire.go:
var modelConverter = copy_helper.NewModelConverter() // Khởi tạo một lần

func InitUserRouterHandler() (*controller.UserController, error) {
	iUserRepository := repositories.NewUserRepository()
	iUserService := services.NewUserService(iUserRepository, modelConverter)
	userController := controller.NewUserController(iUserService)
	return userController, nil
}
