// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: 00001_user.sql

package database

import (
	"context"
	"database/sql"
)

const create = `-- name: Create :execresult
insert into ` + "`" + `users` + "`" + ` (
  first_name, last_name, email, ` + "`" + `password` + "`" + `,
  created_at, updated_at
) values (
  ?, ?, ?, ?, NOW(), NOW()
)
`

type CreateParams struct {
	FirstName string
	LastName  string
	Email     string
	Password  string
}

func (q *Queries) Create(ctx context.Context, arg CreateParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, create,
		arg.FirstName,
		arg.LastName,
		arg.Email,
		arg.Password,
	)
}

const findByEmail = `-- name: FindByEmail :one
select id, first_name, last_name, email, password, created_at, updated_at
from ` + "`" + `users` + "`" + `
where email = ?
`

func (q *Queries) FindByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, findByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.Password,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findById = `-- name: FindById :one
select id, first_name, last_name, email, password, created_at, updated_at
from ` + "`" + `users` + "`" + `
where id = ?
`

func (q *Queries) FindById(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRowContext(ctx, findById, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.Password,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateById = `-- name: UpdateById :exec
update ` + "`" + `users` + "`" + ` 
set
  first_name = coalesce(?, first_name),
  last_name = coalesce(?, last_name),
  updated_at = NOW()
where id = ?
`

type UpdateByIdParams struct {
	FirstName sql.NullString
	LastName  sql.NullString
	ID        sql.NullInt64
}

func (q *Queries) UpdateById(ctx context.Context, arg UpdateByIdParams) error {
	_, err := q.db.ExecContext(ctx, updateById, arg.FirstName, arg.LastName, arg.ID)
	return err
}
