// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: 00002_user_verify.sql

package database

import (
	"context"
	"database/sql"
)

const insertUserVerify = `-- name: InsertUserVerify :exec
insert into user_verify (
  verify_otp,
  verify_key,
  verify_key_hash,
  verify_type
) values (
  ?, ?, ?, ?
)
`

type InsertUserVerifyParams struct {
	VerifyOtp     string
	VerifyKey     string
	VerifyKeyHash string
	VerifyType    sql.NullInt32
}

func (q *Queries) InsertUserVerify(ctx context.Context, arg InsertUserVerifyParams) error {
	_, err := q.db.ExecContext(ctx, insertUserVerify,
		arg.VerifyOtp,
		arg.VerifyKey,
		arg.VerifyKeyHash,
		arg.VerifyType,
	)
	return err
}
