// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package database

import (
	"time"
)

type UserBase struct {
	UserID        int64
	UserEmail     string
	UserPassword  string
	UserSalt      string
	UserCreatedAt time.Time
	UserUpdatedAt time.Time
}
