server:
  port: 5000
  mode: "dev"
mysql:
  host: 127.0.0.1
  port: 8811
  username: "root"
  password: "123456"
  dbName: "user-service"
  maxIdleConns: 10
  maxOpenConns: 100
  connMaxLifetime: 3600
jwt:
  TOKEN_HOUR_LIFESPAN: 1
  JWT_EXPIRATION: 1h
  API_SECRET: "xxx.yyy.zzz"
salt: 16
redis:
  host: 127.0.0.1
  port: 8812
  password: 123456
  database: 0
logger:
  log_level: debug
  file_log_name: "./storages/logs/dev.001.log"
  max_backups: 30
  max_age: 7
  max_size: 1024
  compress: true
